-- Fikir Akademisi - Başlangıç Kitap Verileri
-- Supabase Dashboard > SQL Editor > Run yapın

INSERT INTO books (id, title, author, category, cover_url, total_pages, description, chapter_title, chapter_subtitle, illustration_url, quote, content, tags) VALUES
('insan-neyle-yasar', 'İnsan Neyle Yaşar?', 'Lev Tolstoy', 'Klasikler', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&q=80', 180, 'Yaşamın anlamını arayan bir adamın, basit bir çiftçi aracılığıyla bulduğu derin hikaye.', 'Bölüm 1', 'Yoldaşlar', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80', 'İnsan sevgiyle yaşar, sevgi olmadan hayatı sürer, yaşamaz.', ARRAY['İnsanlar birbirlerinden nefret ederler, çünkü birbirlerinden korkarlar; birbirlerinden korkarlar, çünkü birbirlerini tanımazlar; birbirlerini tanımazlar, çünkü birbirleriyle temas etmezler.', 'Gerçek hayattan kaçmak için kitap okumak, hayatı anlamak için kitap okumaktan çok farklı bir şeydir.'], ARRAY['Felsefe', 'Yaşam', 'Klasik']),

('1984', '1984', 'George Orwell', 'Klasikler', 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80', 352, 'Totaliter rejimlerin gözetleme toplumunu ve düşünce özgürlüğünün bastırılmasını anlatan kült distopya.', 'Kısım 1: Bölüm 1', 'Büyük Birader Seni İzliyor', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80', 'Geçmişi kontrol eden geleceği kontrol eder; bugünü kontrol eden geçmişi kontrol eder.', ARRAY['Hava açık ve soğuk bir nisan günüydü; saatler on üçü vuruyordu. Winston Smith, dondurucu rüzgardan kaçmak için çenesini göğsüne gömmüş, camlı kapıdan Hürriyet Apartmanları''na girdi.', 'Koridorun ucunda, her seferinde karşı tarafın duvarında asılı bir poster, Großen Auge''nun (Büyük Göz) gözleriyle takip ediyordu.', 'Winston, midesindeki o acı çeken boşluğu hissetti. Onun için geçmiş, kayıp bir cennetti.'], ARRAY['Distopya', 'Politika', 'Gözetleme']),

('sapiens', 'Sapiens: İnsan Türünün Kısa Tarihi', 'Yuval Noah Harari', 'Tarih', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&auto=format&fit=crop&q=80', 498, 'İnsan türünün avcı-toplayıcıdan günümüz teknoloji çağına uzanan macerasını anlatan devasa bir tarih öyküsü.', 'Bölüm 1', 'Bilişsel Devrim', 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&auto=format&fit=crop&q=80', 'Biz hayal edebildiğimiz her şeyi yaratabiliriz.', ARRAY['Yaklaşık 70.000 yıl önce, Homo sapiens türü Bilişsel Devrim geçirdi. Bu devrim, hayal edebilme yeteneğini getirdi.', 'Hayal gücü, sapiens''in büyük gruplarda işbirliği yapmasını sağlayan tek şeydir. Dinler, uluslar, para, kanunlar hepsi "ortak hayaller"dir.'], ARRAY['Tarih', 'Antropoloji', 'Bilim']),

('donusum', 'Dönüşüm', 'Franz Kafka', 'Edebiyat', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80', 128, 'Bir gecenin sabahı uyandığında dev bir böceğe dönüşmüş olan Gregor Samsa''nın trajik hikayesi.', 'Bölüm 1', 'Dönüşüm', 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&auto=format&fit=crop&q=80', 'Ben bir böceğim, öyle bir böceğim ki...', ARRAY['Bir sabah, Gregor Samsa huzursuz rüyalarından uyanınca, yatağında dev bir böceğe dönüşmüş olduğunu fark etti.', 'Sert, zırhlı sırtı ve karıncasına bacaklarıyla yatağın üzerinde yatıyordu.'], ARRAY['Varoluşçuluk', 'Aile', 'Absürd']),

('arch-happiness', 'The Architecture of Happiness', 'Alain de Botton', 'Felsefe', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80', 320, 'Binaların, mekanların ve mimarinin insan psikolojisi ve mutluluğu üzerindeki derin etkilerini inceleyen felsefi bir başyapıt.', 'Chapter 3', 'The Importance of Shelter', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80', 'We need our rooms to align us to desirable versions of ourselves.', ARRAY['It is an enduring human trait to seek spaces that reflect our aspirations. The buildings we inhabit are not merely physical shelters; they are psychological armatures.', 'Consider the difference between a cramped, poorly lit corridor and a sweeping, sunlit atrium. The former may induce anxiety, while the latter can inspire a sense of possibility.'], ARRAY['Mimarlık', 'Felsefe', 'Psikoloji']);
